[project]
name = "KPM"
version = "0.1.0"
description = "KPM"
readme = "README.md"
requires-python = ">=3.8, <4.0"

[tool.nonebot]
adapters = [
    { name = "开黑啦", module_name = "nonebot.adapters.kaiheila" }
]
plugins = []
plugin_dirs = ["plugins"]
builtin_plugins = []
